config/routes.rb
Rails.application.routes.draw do

  match '/' => 'video#index', :as => :root, via: [:get, :post]

  resources :video do
    collection do
      post :add_tag
    end
  end

  resources :user do
    collection do
      post 'signin'
      get 'signout'
    end
  end

  namespace :admin do
    resources :video do
      collection do
        post :save
      end
    end

    resources :monitors
  end

  match '/admin' => 'admin/video#index', :as => :admin, via: [:get, :post]

end

app/models/video.rb
class Video < ActiveRecord::Base

  # attr_accessible :name, :autonym, :filename, :tags, :category, :play_url
  
  # before_save :update_tags

  CATEGORY_ITEMS = %w{
    Movie
    Animation
    Learn
    3DH
  }

  def tag_list
    return [] unless tags

    tags.split(',')
  end

  def src_url
    if self.play_url.present?
      url = upload_url
    else
      url = local_url
    end
    url
  end

  def upload_url
    src = "/upload/video/"
    src << self.play_url
  end

  def local_url
    src = "/video/"
    if self.autonym.present?
      unless self.filename.blank?
        src << self.filename
        src << "/"
      end
      src << self.autonym
    else
      src << "default.mp4"
    end
  end
end

app/controllers/admin/video_controller.rb
class Admin::VideoController < AdminController

  def index
    conditions = {}
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:category] = params[:video][:category] if params[:video].present? && params[:video][:category].present?

    filtered_apps = conditions.present? ? Video.where(conditions) : Video
    filtered_apps = filtered_apps.where("tags like ?", "%#{params[:tag]}%") if params[:tag].present?

    @videos = filtered_apps.order('id DESC').paginate :page => params[ :page ],
                         :per_page => PER_PAGE
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if params[:video][:file].present?
      file = params[:video][:file]
      filename = UploadService.new.uploadfile(file)
      @video.play_url = filename+".mp4"
    end

    update_tags

    if @video.save
      flash[:notice] = %Q[Added video "#{@video.name}"]
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @video = Video.find_by_id( params[ :id ] ) || Video.new
  end

  def save
    @video = Video.find_by_id( params[ :id ] )

    update_tags

    unless @video.update( video_params )
      flash[ :error ] = "Failed to save video."
      render :action => 'edit'
      return
    end
    redirect_to :action => :index
  end

  def destroy
    @video = Video.find_by_id( params[ :id ] )
    @video.destroy
    redirect_to :action => :index
  end

private

  def video_params
    params.require(:video).permit(:name, :autonym, :filename, :tags, :category)
  end

  def update_tags
    if params[ :video ][ :tags ] && params[ :video ][ :tags ].present?
      tags_arr = params[ :video ][ :tags ].split(',')
      Tag.update_tags( tags_arr )
    end
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  layout 'home'

  before_filter :video_required, :only => [ :show, :add_tag ]

  def index
    conditions = {}
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:id] = params[:app_default][:id] if params[:app_default].present? && params[:app_default][:id].present?
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:category] = params[:video][:category] if params[:video].present? && params[:video][:category].present?
    conditions[:category] = "Movie" if conditions[:category].blank?

    filtered_apps = conditions.present? ? Video.where(conditions) : Video
    filtered_apps = filtered_apps.where("tags like ?", "%#{params[:tag]}%") if params[:tag].present?

    @videos = filtered_apps.order('id DESC').paginate :page => params[ :page ],
                         :per_page => PER_PAGE
  end

  def show
    @src = @video.src_url
    @tag_list = @video.tag_list
  end

  def add_tag
    if params[ :tags ] && params[ :tags ].present?
      # step 1
      tags_arr = params[ :tags ].split(',')
      Tag.update_tags( tags_arr )
      # step 2
      tags_str = @video.tags || ""
      tags_str = tags_str.clone

      tags_list = @video.tag_list
      tags_arr.each do |tag|
        tags_str << "," unless tags_str == ""
        tags_str << tag unless tags_list.include?(tag)
      end

      @video.tags = tags_str
      
      @video.save
    end
    # @tag_list = @video.tag_list
    redirect_to :action => 'show', :id => @video 
  end

protected
  
  def video_required
    @video = Video.find_by_id( params[ :id ] ) if params[ :id ].present?
    render_api_error( :message => 'Unknown video' ) unless @video
  end

end

app/helpers/admin/video_helper.rb
module Admin::VideoHelper
  def category_items
    items = Hash.new
    Video::CATEGORY_ITEMS.each do |item|
      add_item_to_hash( items, item, "/admin/video?category=#{item}" )
    end
    items
  end

  def tag_items
    items = Hash.new

    Tag.all.each do |tag|
      add_item_to_hash( items, tag.name, "/admin/video?tag=#{tag.name}" )
    end
    items
  end

  def tag_items_arr
    items = Array.new
    Tag.all.each do |tag|
      items << tag.name
    end
    items
  end

protected

  def add_item_to_hash( hash, key, value )
    hash[ key ] = value if hash.is_a? Hash
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def video_list_by_tags
    @tag_list ||= []

    sort_videos = Hash.new
    found_videos = Hash.new
    video_arr = []

    @tag_list.each do |tag|
      Video.where("id != ? AND tags like ?", @video.id, "%#{tag}%").each do |video|
        found_videos[ video.id ] = video unless found_videos.has_key?(video.id)

        if sort_videos.has_key?(video.id)
          sort_videos[ video.id ] = sort_videos[ video.id ] + 1
        else
          sort_videos[ video.id ] = 0
        end
      end
    end

    sort_videos.sort{|a,b| b[1] <=> a[1]}.first(10).each do |arr|
      video_arr << found_videos[ arr[0] ] if found_videos.has_key?(arr[0])
    end

    return video_arr
  end

  def category_items
    items = Hash.new
    Video::CATEGORY_ITEMS.each do |item|
      add_item_to_hash( items, item, "/video?category=#{item}" )
    end
    items
  end

  def tag_items
    items = Hash.new

    Tag.all.each do |tag|
      add_item_to_hash( items, tag.name, "/video?tag=#{tag.name}" )
    end
    items
  end

  def tag_items_arr
    items = Array.new
    Tag.all.each do |tag|
      items << tag.name
    end
    items
  end

protected

  def add_item_to_hash( hash, key, value )
    hash[ key ] = value if hash.is_a? Hash
  end
end

app/views/video/index.html.erb
<div class="center-block">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Video</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/admin/video/new">New</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Category <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% category_items.each do |key, value| %>
                <li><a href="<%= value%>"><%= key%></a></li>
              <% end %>
            </ul>
          </li>
        </ul>

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tags <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% tag_items.each do |key, value| %>
                <li><a href="<%= value%>"><%= key%></a></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Watch</th>
      </tr>
    </thead>
    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.name%></td>
          <td><%= video.autonym%></td>
          <td><%= link_to "Play", video_path(video) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @videos %>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

app/views/video/show.html.erb
<div class="page-header">
  <span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>
  <b><%=@video.name %></b>
  <br>
  <br>
  <a href="<%= @src %>" download="<%= @video.autonym %>">Download</a>
</div>

<div class="row">
  <div class="col-md-8 pull-left">
    <video id="<%=@video.id %>" class="video-js vjs-default-skin vjs-big-play-centered"
    controls preload="auto" width="620" height="460">
      <source src="<%= @src %>" type="video/mp4">
      Your browser does not support the video tag.
    </video>
  </div>

  <div class="col-md-4 list-group pull-right">
    <a href="#" class="list-group-item active">
      Cras justo odio
    </a>
    <% video_list_by_tags.each do |video| %>
      <a href="/video/<%= video.id%>" class="list-group-item" data-toggle="tooltip" data-placement="bottom" title="<%= video.tags%>"><%= video.name%></a>
    <% end %>
  </div>
</div>

<div class="add-tag-div">
  <!-- <form class="form-inline">  '/user/signin'-->
  <%= form_tag( {:action => 'add_tag', :controller => 'video'}, {:class => 'form-inline'} ) do -%>
    <div class="hidden">
      <label for="exampleInputVideoId">Tags</label>
      <input type="text" name="id" class="form-control" id="exampleInputVideoId" value=<%= @video.id %>>
    </div>
    <div class="form-group">
      <label for="exampleInputTags">Tags</label>
      <input type="text" name="tags" class="form-control" id="exampleInputTags" placeholder="add tags, please split by ','">
    </div>
    <button type="submit" class="btn btn-default">Add</button>
  <% end -%>
</div>

<div class="add-tag-div">
  <% @tag_list.each do |tag| %>
    <a href=""><span class="label label-primary"><%= tag%></span></a>
  <% end %>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>