config/routes.rb
Rails.application.routes.draw do

  match '/' => 'video#index', :as => :root, via: [:get, :post]

  resources :video do
    collection do
      post :add_tag
    end
  end

  resources :user do
    collection do
      post 'signin'
      get 'signout'
    end
  end

  namespace :admin do
    resources :video do
      collection do
        post :save
      end
    end

    resources :monitors
  end

  match '/admin' => 'admin/video#index', :as => :admin, via: [:get, :post]

end

app/models/video.rb
class Video < ActiveRecord::Base

  # attr_accessible :name, :autonym, :filename, :tags, :category, :play_url
  
  # before_save :update_tags

  CATEGORY_ITEMS = %w{
    Movie
    Animation
    Learn
    3DH
  }

  def tag_list
    return [] unless tags

    tags.split(',')
  end

  def src_url
    if self.play_url.present?
      url = upload_url
    else
      url = local_url
    end
    url
  end

  def upload_url
    src = "/upload/video/"
    src << self.play_url
  end

  def local_url
    src = "/video/"
    if self.autonym.present?
      unless self.filename.blank?
        src << self.filename
        src << "/"
      end
      src << self.autonym
    else
      src << "default.mp4"
    end
  end
end

app/controllers/admin/video_controller.rb
class Admin::VideoController < AdminController

  def index
    conditions = {}
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:category] = params[:video][:category] if params[:video].present? && params[:video][:category].present?

    filtered_apps = conditions.present? ? Video.where(conditions) : Video
    filtered_apps = filtered_apps.where("tags like ?", "%#{params[:tag]}%") if params[:tag].present?

    @videos = filtered_apps.order('id DESC').paginate :page => params[ :page ],
                         :per_page => PER_PAGE
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if params[:video][:file].present?
      file = params[:video][:file]
      filename = UploadService.new.uploadfile(file)
      @video.play_url = filename+".mp4"
    end

    update_tags

    if @video.save
      flash[:notice] = %Q[Added video "#{@video.name}"]
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @video = Video.find_by_id( params[ :id ] ) || Video.new
  end

  def save
    @video = Video.find_by_id( params[ :id ] )

    update_tags

    unless @video.update( video_params )
      flash[ :error ] = "Failed to save video."
      render :action => 'edit'
      return
    end
    redirect_to :action => :index
  end

  def destroy
    @video = Video.find_by_id( params[ :id ] )
    @video.destroy
    redirect_to :action => :index
  end

private

  def video_params
    params.require(:video).permit(:name, :autonym, :filename, :tags, :category)
  end

  def update_tags
    if params[ :video ][ :tags ] && params[ :video ][ :tags ].present?
      tags_arr = params[ :video ][ :tags ].split(',')
      Tag.update_tags( tags_arr )
    end
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  layout 'home'

  before_filter :video_required, :only => [ :show, :add_tag ]

  def index
    conditions = {}
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:id] = params[:app_default][:id] if params[:app_default].present? && params[:app_default][:id].present?
    conditions[:category] = params[:category] if params[:category].present?
    # conditions[:category] = params[:video][:category] if params[:video].present? && params[:video][:category].present?
    conditions[:category] = "Movie" if conditions[:category].blank?

    filtered_apps = conditions.present? ? Video.where(conditions) : Video
    filtered_apps = filtered_apps.where("tags like ?", "%#{params[:tag]}%") if params[:tag].present?

    @videos = filtered_apps.order('id DESC').paginate :page => params[ :page ],
                         :per_page => PER_PAGE
  end

  def show
    @src = @video.src_url
    @tag_list = @video.tag_list
  end

  def add_tag
    if params[ :tags ] && params[ :tags ].present?
      # step 1
      tags_arr = params[ :tags ].split(',')
      Tag.update_tags( tags_arr )
      # step 2
      tags_str = @video.tags || ""
      tags_str = tags_str.clone

      tags_list = @video.tag_list
      tags_arr.each do |tag|
        tags_str << "," unless tags_str == ""
        tags_str << tag unless tags_list.include?(tag)
      end

      @video.tags = tags_str
      
      @video.save
    end
    # @tag_list = @video.tag_list
    redirect_to :action => 'show', :id => @video 
  end

protected
  
  def video_required
    @video = Video.find_by_id( params[ :id ] ) if params[ :id ].present?
    render_api_error( :message => 'Unknown video' ) unless @video
  end

end

app/helpers/admin/video_helper.rb
module Admin::VideoHelper
  def category_items
    items = Hash.new
    Video::CATEGORY_ITEMS.each do |item|
      add_item_to_hash( items, item, "/admin/video?category=#{item}" )
    end
    items
  end

  def tag_items
    items = Hash.new

    Tag.all.each do |tag|
      add_item_to_hash( items, tag.name, "/admin/video?tag=#{tag.name}" )
    end
    items
  end

  def tag_items_arr
    items = Array.new
    Tag.all.each do |tag|
      items << tag.name
    end
    items
  end

protected

  def add_item_to_hash( hash, key, value )
    hash[ key ] = value if hash.is_a? Hash
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def video_list_by_tags
    @tag_list ||= []

    sort_videos = Hash.new
    found_videos = Hash.new
    video_arr = []

    @tag_list.each do |tag|
      Video.where("id != ? AND tags like ?", @video.id, "%#{tag}%").each do |video|
        found_videos[ video.id ] = video unless found_videos.has_key?(video.id)

        if sort_videos.has_key?(video.id)
          sort_videos[ video.id ] = sort_videos[ video.id ] + 1
        else
          sort_videos[ video.id ] = 0
        end
      end
    end

    sort_videos.sort{|a,b| b[1] <=> a[1]}.first(10).each do |arr|
      video_arr << found_videos[ arr[0] ] if found_videos.has_key?(arr[0])
    end

    return video_arr
  end

  def category_items
    items = Hash.new
    Video::CATEGORY_ITEMS.each do |item|
      add_item_to_hash( items, item, "/video?category=#{item}" )
    end
    items
  end

  def tag_items
    items = Hash.new

    Tag.all.each do |tag|
      add_item_to_hash( items, tag.name, "/video?tag=#{tag.name}" )
    end
    items
  end

  def tag_items_arr
    items = Array.new
    Tag.all.each do |tag|
      items << tag.name
    end
    items
  end

protected

  def add_item_to_hash( hash, key, value )
    hash[ key ] = value if hash.is_a? Hash
  end
end

app/views/admin/video/edit.html.erb
<% flash.each do |msg_type, message| %>
  <p style="color: red;"><%= message%></p>
<% end %>

<%= form_for( @video, :as => :video,
             :url => { :controller => '/admin/video', :action => 'save', :id => @video },
             :html => { :method => :post, :multipart => true } ) do |f| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= f.text_field :name, :class => "form-control" %>
  <div class="form-group">
    <label for="autonym">Autonym</label>
    <%= f.text_field :autonym, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="filename">File</label>
    <%= f.text_field :filename, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="category">Category</label>
    <%= f.select :category, Video::CATEGORY_ITEMS, {}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <label for="tags">Tags</label>
    <%= f.text_field :tags, :class => "form-control" %>
  </div>
  <button type="submit" class="btn btn-default">Save</button>
  <a href="/admin/video" class="btn btn-primary pull-right">Back</a>
<% end %>

app/views/admin/video/index.html.erb
<div class="center-block">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Video</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/admin/video/new">New</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Category <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% category_items.each do |key, value| %>
                <li><a href="<%= value%>"><%= key%></a></li>
              <% end %>
            </ul>
          </li>
        </ul>

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tags <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% tag_items.each do |key, value| %>
                <li><a href="<%= value%>"><%= key%></a></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Autonym</th>
          <th>Category</th>
          <th>Tags</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @videos.each do |video| %>
          <tr>
            <td><%= video.name%></td>
            <td><%= video.autonym%></td>
            <td><%= video.category%></td>
            <td><a tabindex="0" class="btn btn-sm btn-warning" role="button" data-toggle="popover" data-trigger="focus" title="Tags" data-content="<%= video.tags%>">tags</a></td>
            <td><%= link_to "Edit", edit_admin_video_path(video) %></td>
            <td><%= button_to "Delete", admin_video_path(video), :method => :delete, :class =>"btn btn-default btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @videos %>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

app/views/admin/video/new.html.erb
<% flash.each do |msg_type, message| %>
  <p style="color: red;"><%= message%></p>
<% end %>

<%= form_for( @video, :as => :video,
             :url => { :controller => '/admin/video', :action => 'create', :id => @video },
             :html => { :method => :post, :multipart => true } ) do |f| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= f.text_field :name, :class => "form-control" %>
  <div class="form-group">
    <label for="autonym">Autonym</label>
    <%= f.text_field :autonym, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="filename">File</label>
    <%= f.text_field :filename, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="category">Category</label>
    <%= f.select :category, Video::CATEGORY_ITEMS, {}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <label for="tags">Tags</label>
    <%= f.text_field :tags, :class => "form-control" %>
  </div>
  <hr />
  <div class="form-group">
    <label for="filename">File</label>
    <%= f.file_field :file, :class => "form-control" %>
  </div>
  <button type="submit" class="btn btn-default">Create</button>
  <a href="/admin/video" class="btn btn-primary pull-right">Back</a>
<% end %>