config/routes.rb
Rails.application.routes.draw do

  match '/' => 'video#index', :as => :root, via: [:get, :post]

  resources :video do
    collection do
      post :add_tag
    end
  end

  resources :user do
    collection do
      post 'signin'
      get 'signout'
    end
  end

  namespace :admin do
    resources :video do
      collection do
        post :save
      end
    end

    resources :monitors
  end

  match '/admin' => 'admin/video#index', :as => :admin, via: [:get, :post]

end

app/controllers/admin/monitors_controller.rb
class Admin::MonitorsController < AdminController
  before_action :set_monitor, only: [:show, :edit, :update, :destroy]

  def index
    # @admin_monitors = Admin::Monitor.all
    @used, @total = MonitorService.new.show_disk_info
  end

  # GET /admin/monitors/1
  # GET /admin/monitors/1.json
  def show
  end

  # GET /admin/monitors/new
  def new
  end

  # GET /admin/monitors/1/edit
  def edit
  end

  # POST /admin/monitors
  # POST /admin/monitors.json
  def create
  end

  # PATCH/PUT /admin/monitors/1
  # PATCH/PUT /admin/monitors/1.json
  def update
  end

  # DELETE /admin/monitors/1
  # DELETE /admin/monitors/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_monitor
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_monitor_params
      params[:admin_monitor]
    end
end

app/helpers/admin/monitors_helper.rb
module Admin::MonitorsHelper
end

app/views/admin/monitors/_form.html.erb
<%= form_for(@admin_monitor) do |f| %>
  <% if @admin_monitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_monitor.errors.count, "error") %> prohibited this admin_monitor from being saved:</h2>

      <ul>
      <% @admin_monitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/monitors/edit.html.erb
<h1>Editing admin_monitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_monitor %> |
<%= link_to 'Back', admin_monitors_path %>

app/views/admin/monitors/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Monitor</h3>
  </div>
  <div class="panel-body">
    <div class="well">
      <p>Disk Total: <b><%= @total/1024 %> G</b></p>
      <p>Used: <b><%= @used %> M</b></p>
    </div>
  </div>
</div>

app/views/admin/monitors/new.html.erb
<h1>New admin_monitor</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_monitors_path %>

app/views/admin/monitors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_monitor_path(@admin_monitor) %> |
<%= link_to 'Back', admin_monitors_path %>